# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 16:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='complain',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('complaint_date', models.DateTimeField(auto_now_add=True)),
                ('complaint_type', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=50)),
                ('specific_location', models.CharField(max_length=50)),
                ('details', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'complaint',
            },
        ),
    ]
