# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 17:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complain',
            name='complaint_type',
        ),
        migrations.AlterField(
            model_name='complain',
            name='complaint_date',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='complain',
            name='id',
            field=models.CharField(max_length=50, primary_key=True, serialize=False),
        ),
    ]
